fix: handle self being undefined
getSelf() can return undefined so that case must be handled,  otherwise the following error will occur:
TypeError: Cannot read properties of undefined (reading 'default_org_context')